variable "tags_context" {
  type = object({
    enabled             = bool
    name                = string
    namespace           = string
    environment         = string
    stage               = string
    attributes          = list(string)
    tags                = map(string)
    delimiter           = string
    label_order         = list(string)
    regex_replace_chars = string
    additional_tag_map  = map(string)
  })
  description = "Context map generated by terraform-null-label module"
}

variable "additional_ebs" {
  type = list(object({
    device_name = string
    volume_type = string
    volume_size = string
    iops        = number
    kms_key_id  = string
    device_name = string
  }))
  default = [
    {
      device_name = "NA"
      volume_type = "NA"
      volume_size = "NA"
      iops        = 0
      kms_key_id  = "NA"
    }
  ]
}

variable "instance_type" {
  description = "instance size"
}

variable "key_name" {
  description = "SSH Key to access instance"
  default     = ""
}

variable "monitoring" {
  description = "If true, the launched EC2 instance will have detailed monitoring enabled."
  default     = false
}

variable "ebs_optimized" {
  description = "If true, the launched EC2 instance will be EBS-optimized"
  default     = true
}

variable "subnet_id" {
  description = "The VPC Subnet ID to launch in."
}

variable "env" {
  description = "Instance environemnt"
}

variable "component" {
  description = "Instance role"
}

variable "volume_type" {
  description = "The type of volume."
  default     = "gp3"
}

variable "volume_size" {
  description = "The size of the volume in gigabytes"
  default     = "100"
}

variable "security_groups" {
  type        = list(string)
  description = "Hook to existing security group"
}

variable "aws_ami_id" {
  description = "AMI Id"
}

variable "enabled" {
  type        = bool
  description = "Set to false to prevent the module from creating any resources"
  default     = true
}

variable "encrypted" {
  type    = bool
  default = true
}

variable "kms_key_id" {
  type    = string
  default = ""
}

variable "static_ips" {
  type        = list(string)
  default     = []
  description = "Use if you need to set one or more static IP addresses.  This will create non-default network interfaces that are attached to the instance"
}

variable "disable_api_termination" {
  default = false
}

variable "get_password_data" {
  type        = bool
  default     = false
  description = "(optional) If true, wait for password data to become available and retrieve it. Useful for getting the administrator password for instances running Microsoft Windows. The password data is exported to the password_data attribute."
}

variable "iam_instance_profile" {
  type        = string
  default     = ""
  description = "(optional) The IAM Instance Profile to launch the instance with. Specified as the name of the Instance Profile."
}
