variable "tags_context" {
  type = object({
    enabled             = bool
    name                = string
    namespace           = string
    environment         = string
    stage               = string
    attributes          = list(string)
    tags                = map(string)
    delimiter           = string
    label_order         = list(string)
    regex_replace_chars = string
    additional_tag_map  = map(string)
  })
  description = "Context map generated by terraform-null-label module"
}

variable "enable" {
  type    = bool
  default = true
}

variable "name" {
  type        = string
  description = "Name of Cluster"
}

variable "kube_version" {
  type        = string
  description = "Kubernetes version"
}

variable "access_ips" {
  type        = list(string)
  description = "CIDR blocks to allow inbound traffic"
}

variable "env" {
  type        = string
  description = "Environment"
}

variable "log_types" {
  type        = list(string)
  description = "A list of the desired control plane logging to enable."
}

variable "log_retention_in_days" {
  default     = 7
  description = "Specifies the number of days you want to retain log events in the specified log group."
}

variable "enable_private_access" {
  type        = bool
  default     = false
  description = "Indicates whether or not the Amazon EKS private API server endpoint is enabled."
}

variable "enable_public_access" {
  type        = bool
  default     = false
  description = "Indicates whether or not the Amazon EKS public API server endpoint is enabled."
}

variable "public_access_cidrs" {
  type        = list(string)
  default     = []
  description = "List of CIDR blocks. Indicates which CIDR blocks can access the Amazon EKS public API server endpoint when enabled."
}

variable "admin_sso_role" {
  description = "SSO Admin role for KMS Key administration."
}

variable "cni_version" {
  default     = ""
  type        = string
  description = "CNI plugin addon version"
}

variable "kubeproxy_version" {
  default     = ""
  type        = string
  description = "Kube Proxy plugin addon version"
}

variable "coredns_version" {
  default     = ""
  type        = string
  description = "Core DNS plugin addon version"
}

variable "secrets_kms_arn" {
  default = []
  type    = list(string)
  description = "KMS key ARN for encrypting secrets (only one arn in list)"
}

