#!/bin/bash

if [[ ($# -ne 1 && $# -ne 2) || $1 == '--help' ]]; then
    echo 'Usage: fetch "URL" [dest-dir]'
    exit 0
fi

if [ $1 == '--mean' ]; then
    open "https://www.youtube.com/watch?v=Pubd-spHN-0"
    exit 0
fi

function urldecode() {
    echo "$1/$(: "${_##*/}"; : "${_//+/ }"; echo -e "${_//%/\\x}")"
}

if [ $# -eq 2 ]; then
    wget -nc -P "$2" "$1"
    open "$(urldecode "$2")"
else
    wget -nc "$1"
    open "$(urldecode .)"
fi
